import { RANDOM_HASHTAG_POOL, REQUIRED_HASHTAGS } from "@/lib/hashtags";
import { NEGATIVE_PHRASE_RULES } from "./negative-feedback";

export type ComplianceCategory =
  | "absolute"
  | "authority"
  | "clickbait"
  | "fomo"
  | "medical"
  | "cosmetic"
  | "superstition"
  | "platform"
  | "traffic"
  | "hard-sell"
  | "visual"
  | "sensitive"
  | "negative";

export type PhraseRule = {
  phrase: string;
  category: ComplianceCategory;
  replacement: string;
};

export const REQUIRED_SAFE_HASHTAGS = [...REQUIRED_HASHTAGS, ...RANDOM_HASHTAG_POOL] as const;

/** Exact phrases, longest-first at runtime. Required hashtags are allowlisted separately. */
export const PHRASE_RULES: PhraseRule[] = [
  { phrase: "这家店直接封神", category: "absolute", replacement: "这家店给我的感觉很不错" },
  { phrase: "最好吃的泰餐", category: "hard-sell", replacement: "最近很喜欢的一家泰餐" },
  { phrase: "曼谷必吃泰餐", category: "hard-sell", replacement: "曼谷泰餐推荐" },
  { phrase: "直接封神", category: "absolute", replacement: "这次吃下来印象很好" },
  { phrase: "曼谷必吃清单", category: "hard-sell", replacement: "曼谷探店清单" },
  { phrase: "中国驰名商标", category: "authority", replacement: "日常在用的品牌" },
  { phrase: "质量免检", category: "authority", replacement: "用起来比较放心" },
  { phrase: "国际领先", category: "authority", replacement: "风格比较精致" },
  { phrase: "行业领先", category: "authority", replacement: "体验比较稳定" },
  { phrase: "世界领先", category: "absolute", replacement: "这次吃下来印象不错" },
  { phrase: "全球首发", category: "absolute", replacement: "最近才吃到" },
  { phrase: "全国首家", category: "absolute", replacement: "一家挺有特点的店" },
  { phrase: "史无前例", category: "absolute", replacement: "这次体验比较特别" },
  { phrase: "绝无仅有", category: "absolute", replacement: "挺少见的体验" },
  { phrase: "独一无二", category: "absolute", replacement: "挺有自己风格" },
  { phrase: "第一品牌", category: "absolute", replacement: "常会想到的品牌" },
  { phrase: "销量冠军", category: "absolute", replacement: "人气比较高" },
  { phrase: "全网第一", category: "absolute", replacement: "最近讨论比较多" },
  { phrase: "销量第一", category: "absolute", replacement: "点的人不少" },
  { phrase: "曼谷第一", category: "hard-sell", replacement: "曼谷比较喜欢的一家" },
  { phrase: "没有之一", category: "absolute", replacement: "属于我比较喜欢的" },
  { phrase: "天花板级别", category: "absolute", replacement: "整体体验比较不错" },
  { phrase: "全网都在买", category: "absolute", replacement: "最近看到的人不少" },
  { phrase: "全网爆火", category: "hard-sell", replacement: "最近挺多人提起" },
  { phrase: "全网爆红", category: "hard-sell", replacement: "最近挺多人提起" },
  { phrase: "网红必吃", category: "hard-sell", replacement: "很多人会来这里吃" },
  { phrase: "米其林级别", category: "hard-sell", replacement: "风格比较精致" },
  { phrase: "米其林餐厅", category: "hard-sell", replacement: "泰式餐厅" },
  { phrase: "绝对不会踩雷", category: "absolute", replacement: "整体体验比较不错" },
  { phrase: "再不抢就没了", category: "fomo", replacement: "最近看到还有活动" },
  { phrase: "不会再便宜了", category: "fomo", replacement: "目前看到的价格还可以" },
  { phrase: "错过就没机会了", category: "fomo", replacement: "想去的话可以先看看档期" },
  { phrase: "万人疯抢", category: "fomo", replacement: "活动期间人气比较高" },
  { phrase: "最后机会", category: "fomo", replacement: "最近还看得到" },
  { phrase: "不买后悔", category: "fomo", replacement: "可以根据自己需要再决定" },
  { phrase: "闭眼入", category: "fomo", replacement: "可以先收藏起来备用" },
  { phrase: "必须买", category: "fomo", replacement: "可以根据自己口味试试" },
  { phrase: "赶紧买", category: "fomo", replacement: "有兴趣可以了解一下" },
  { phrase: "手慢无", category: "fomo", replacement: "最近还看得到" },
  { phrase: "抢疯了", category: "fomo", replacement: "人气比较高" },
  { phrase: "快抢", category: "fomo", replacement: "最近挺多人关注" },
  { phrase: "秒杀", category: "fomo", replacement: "最近有活动" },
  { phrase: "抢购", category: "fomo", replacement: "最近比较热门" },
  { phrase: "买它", category: "fomo", replacement: "可以参考看看" },
  { phrase: "恭喜获奖", category: "clickbait", replacement: "可以收藏起来备用" },
  { phrase: "全民免单", category: "clickbait", replacement: "可以先看看活动说明" },
  { phrase: "点击有惊喜", category: "clickbait", replacement: "有兴趣可以参考看看" },
  { phrase: "点击获取", category: "clickbait", replacement: "可以收藏起来备用" },
  { phrase: "点击试穿", category: "clickbait", replacement: "可以先看看详情" },
  { phrase: "领取奖品", category: "clickbait", replacement: "可以先了解活动规则" },
  { phrase: "转发三连", category: "clickbait", replacement: "喜欢的话可以收藏" },
  { phrase: "一键三连", category: "clickbait", replacement: "喜欢的话可以收藏" },
  { phrase: "免费领取", category: "clickbait", replacement: "可以先看看说明" },
  { phrase: "扫码领取", category: "clickbait", replacement: "可以先看看说明" },
  { phrase: "点击领取", category: "clickbait", replacement: "可以先看看说明" },
  { phrase: "马上领取", category: "clickbait", replacement: "可以先看看说明" },
  { phrase: "私信我获取", category: "traffic", replacement: "帖子里已经写了这次体验" },
  { phrase: "主页有链接", category: "traffic", replacement: "需要的信息我写在这篇里了" },
  { phrase: "扫码进群", category: "traffic", replacement: "有相同喜好可以看看这篇" },
  { phrase: "加微信", category: "traffic", replacement: "有需要的信息都写在正文里了" },
  { phrase: "关注XX账号", category: "traffic", replacement: "这篇把体验写清楚了" },
  { phrase: "完全无P", category: "visual", replacement: "随手拍的，没有修得很夸张" },
  { phrase: "100%真实", category: "visual", replacement: "就是这次吃饭随手拍的" },
  { phrase: "原图直出", category: "visual", replacement: "随手拍的照片" },
  { phrase: "零滤镜", category: "visual", replacement: "没有修得很夸张" },
  { phrase: "绝对真实", category: "visual", replacement: "就是当时拍下来的样子" },
  { phrase: "带来好运", category: "superstition", replacement: "整体心情不错" },
  { phrase: "招财进宝", category: "superstition", replacement: "吃得很开心" },
  { phrase: "健康富贵", category: "superstition", replacement: "吃着很舒服" },
  { phrase: "提升运气", category: "superstition", replacement: "心情会好一点" },
  { phrase: "逢凶化吉", category: "superstition", replacement: "吃完感觉挺放松" },
  { phrase: "时来运转", category: "superstition", replacement: "这次体验挺顺" },
  { phrase: "增强免疫力", category: "medical", replacement: "吃着比较安心" },
  { phrase: "提高免疫力", category: "medical", replacement: "吃着比较安心" },
  { phrase: "清热解毒", category: "medical", replacement: "口感比较清爽" },
  { phrase: "临床证明", category: "medical", replacement: "个人体感还可以" },
  { phrase: "临床观察", category: "medical", replacement: "自己吃下来的感觉" },
  { phrase: "改善失眠", category: "medical", replacement: "吃完比较放松" },
  { phrase: "帮助排毒", category: "medical", replacement: "吃着比较清爽" },
  { phrase: "身体排毒", category: "medical", replacement: "吃着比较清爽" },
  { phrase: "国际品质", category: "authority", replacement: "日常用餐体验" },
  { phrase: "世界级", category: "authority", replacement: "风格比较精致" },
  { phrase: "国家级", category: "authority", replacement: "比较正式的" },
  { phrase: "最高级", category: "absolute", replacement: "比较精致" },
  { phrase: "最先进", category: "absolute", replacement: "用起来比较顺手" },
  { phrase: "最便宜", category: "absolute", replacement: "价格对我来说还可以" },
  { phrase: "最受欢迎", category: "absolute", replacement: "点的人不少" },
  { phrase: "最时尚", category: "absolute", replacement: "风格比较好看" },
  { phrase: "第一梯队", category: "absolute", replacement: "体验比较稳" },
  { phrase: "无人能及", category: "absolute", replacement: "这次印象很好" },
  { phrase: "百分百", category: "absolute", replacement: "整体来说" },
  { phrase: "100%", category: "absolute", replacement: "整体来说" },
  { phrase: "Top 1", category: "absolute", replacement: "比较喜欢" },
  { phrase: "No.1", category: "absolute", replacement: "比较喜欢" },
  { phrase: "TOP1", category: "absolute", replacement: "比较喜欢" },
  { phrase: "顶级泰餐", category: "hard-sell", replacement: "风格比较精致的泰餐" },
  { phrase: "必打卡", category: "hard-sell", replacement: "可以去看看" },
  { phrase: "曼谷必吃", category: "hard-sell", replacement: "曼谷美食" },
  { phrase: "最好吃", category: "hard-sell", replacement: "挺好吃" },
  { phrase: "天花板", category: "absolute", replacement: "比较喜欢" },
  { phrase: "封神", category: "absolute", replacement: "印象很好" },
  { phrase: "无敌", category: "absolute", replacement: "挺加分" },
  { phrase: "极致", category: "absolute", replacement: "很舒服" },
  { phrase: "永久", category: "absolute", replacement: "比较耐用" },
  { phrase: "万能", category: "absolute", replacement: "用途比较广" },
  { phrase: "独家", category: "absolute", replacement: "比较少见" },
  { phrase: "首家", category: "absolute", replacement: "一家" },
  { phrase: "首个", category: "absolute", replacement: "这次吃到的" },
  { phrase: "首选", category: "absolute", replacement: "可以优先考虑" },
  { phrase: "金牌", category: "absolute", replacement: "口碑不错" },
  { phrase: "名牌", category: "authority", replacement: "常见的品牌" },
  { phrase: "王牌", category: "absolute", replacement: "比较有代表性" },
  { phrase: "顶级", category: "hard-sell", replacement: "比较精致" },
  { phrase: "高档", category: "authority", replacement: "环境比较舒服" },
  { phrase: "奢华", category: "authority", replacement: "布置比较用心" },
  { phrase: "著名", category: "authority", replacement: "很多人知道的" },
  { phrase: "大牌", category: "authority", replacement: "常见品牌" },
  { phrase: "正品", category: "authority", replacement: "这次买到的" },
  { phrase: "老字号", category: "authority", replacement: "开了有一段时间" },
  { phrase: "特供", category: "authority", replacement: "店里的" },
  { phrase: "专供", category: "authority", replacement: "店里的" },
  { phrase: "米其林", category: "hard-sell", replacement: "精致" },
  { phrase: "绝对", category: "absolute", replacement: "整体" },
  { phrase: "必买", category: "fomo", replacement: "可以考虑" },
  { phrase: "必吃", category: "hard-sell", replacement: "很喜欢" },
  { phrase: "最佳", category: "absolute", replacement: "比较合适" },
  { phrase: "领先", category: "absolute", replacement: "做得不错" },
  { phrase: "抖音", category: "platform", replacement: "其他平台" },
  { phrase: "快手", category: "platform", replacement: "其他平台" },
  { phrase: "B站", category: "platform", replacement: "其他平台" },
  { phrase: "哔哩哔哩", category: "platform", replacement: "其他平台" },
  { phrase: "微博", category: "platform", replacement: "其他平台" },
  { phrase: "淘宝", category: "platform", replacement: "购物平台" },
  { phrase: "京东", category: "platform", replacement: "购物平台" },
  { phrase: "TikTok", category: "platform", replacement: "其他平台" },
  { phrase: "tiktok", category: "platform", replacement: "其他平台" },
];

const MEDICAL_STEMS = [
  "助眠",
  "消炎",
  "抗炎",
  "抗菌",
  "杀菌",
  "消毒",
  "排毒",
  "减肥",
  "瘦身",
  "瘦脸",
  "瘦腿",
  "祛湿",
  "治疗",
  "治愈",
  "抗敏",
  "脱敏",
  "生发",
  "止脱",
  "祛疤",
  "祛痘",
  "防癌",
  "抗癌",
  "降血压",
  "补肾",
  "活血",
  "安神",
  "通脉",
  "理气",
  "行气",
  "荷尔蒙",
  "激素",
  "抗生素",
  "毛囊激活",
  "毛发再生",
  "细胞再生",
  "细胞修复",
  "美容治疗",
];

const COSMETIC_STEMS = [
  "特效",
  "高效",
  "全效",
  "强效",
  "速效",
  "速白",
  "一洗白",
  "溶脂",
  "吸脂",
  "燃烧脂肪",
  "延年益寿",
  "消除皱纹",
  "永不褪色",
  "迅速修复",
  "更新肌肤",
  "破坏黑色素",
  "阻断黑色素",
  "丰胸",
  "乳房丰满",
  "无毒",
];

const SUPERSTITION_STEMS = [
  "化解小人",
  "增加事业运",
  "护身",
  "旺财",
  "旺人",
  "助吉避凶",
  "转富招福",
  "万事亨通",
  "平衡正负能量",
  "增强第六感",
];

function stemsToRules(
  stems: string[],
  category: ComplianceCategory,
  replacement: string,
): PhraseRule[] {
  return stems.map((phrase) => ({ phrase, category, replacement }));
}

export const EXTRA_STEM_RULES: PhraseRule[] = [
  ...stemsToRules(MEDICAL_STEMS, "medical", "体感比较舒服"),
  ...stemsToRules(COSMETIC_STEMS, "cosmetic", "日常使用体验不错"),
  ...stemsToRules(SUPERSTITION_STEMS, "superstition", "心情比较放松"),
];

export function allPhraseRules() {
  return [...PHRASE_RULES, ...EXTRA_STEM_RULES, ...NEGATIVE_PHRASE_RULES].sort(
    (a, b) => b.phrase.length - a.phrase.length,
  );
}

export const COMPILED_SEMANTIC_PATTERNS = [
  { pattern: /全曼谷都在吃/g, category: "absolute" as const, replacement: "很多人会来这里吃" },
  { pattern: /直接封神/g, category: "absolute" as const, replacement: "这次吃下来印象很好" },
  { pattern: /最好吃的/g, category: "hard-sell" as const, replacement: "挺喜欢的" },
  { pattern: /全网都在/g, category: "absolute" as const, replacement: "最近挺多人" },
  { pattern: /没有之一/g, category: "absolute" as const, replacement: "属于我比较喜欢的" },
  { pattern: /天花板级/g, category: "absolute" as const, replacement: "整体体验比较不错" },
  { pattern: /绝对不会踩雷/g, category: "absolute" as const, replacement: "整体体验比较不错" },
  { pattern: /千万别错过/g, category: "fomo" as const, replacement: "有机会可以去吃吃看" },
  { pattern: /不容错过/g, category: "fomo" as const, replacement: "挺值得去尝尝" },
  { pattern: /必须冲/g, category: "fomo" as const, replacement: "可以去吃吃看" },
  { pattern: /值得冲/g, category: "fomo" as const, replacement: "可以去吃吃看" },
  { pattern: /去[\w\u4e00-\u9fff]{1,8}看完整版/g, category: "traffic" as const, replacement: "这篇已经把体验写清楚了" },
  { pattern: /评论区留联系方式/g, category: "traffic" as const, replacement: "需要的信息都写在正文里了" },
  { pattern: /\d+\s*天(见效|变白|瘦下来)/g, category: "cosmetic" as const, replacement: "用了一段时间体感还可以" },
  { pattern: /让皮肤彻底恢复健康/g, category: "medical" as const, replacement: "使用感比较温和" },
  { pattern: /解决敏感肌/g, category: "medical" as const, replacement: "肤感比较舒服" },
  { pattern: /痘痘都消失/g, category: "medical" as const, replacement: "肤感比较清爽" },
  { pattern: /唯一(?!一次)/g, category: "absolute" as const, replacement: "很少见的" },
];
