import type { BrandContext } from "@/types/campaign";

export const BAAN_YING_BRAND_CONTEXT: BrandContext = {
  story:
    "Baan Ying started as a small restaurant with 8 tables at Siam Square, Bangkok, in 1999. It was created around family recipes and comforting Thai home cooking for people who missed the taste of home. Founder Auntie Ying believes food made for family is the best kind of food, and all customers are treated as part of the Baan Ying family. It later grew into a family business with multiple branches in prime Bangkok locations, while keeping Thai home cooking, family, warmth, comfort, care, sharing food together, fresh ingredients, and authentic Thai taste. The deeper feeling is familiar, comforting, warm, welcoming, and approachable — like eating at home. This is BACKGROUND KNOWLEDGE only. Do not force 1999, Auntie Ying, Siam Square, family recipes, or branch-count history into every post.",
  personality: [
    "Warm",
    "Welcoming",
    "Familiar",
    "Authentic but approachable",
    "Modern Thai",
    "Friendly",
    "Casual",
    "Family-friendly",
  ],
  signature: [
    "Thai home cooking",
    "Family recipes",
    "Comfort food",
    "Family-style dining",
    "Sharing dishes",
    "Fresh ingredients",
    "Welcoming atmosphere",
    "Personalized DIY Pad Kra Pao",
  ],
  approvedFacts: [
    "Established in Thailand in 1999",
    "Known for Thai comfort food",
    "Multiple locations in Bangkok",
    "Suitable for casual dining",
    "Suitable for sharing",
    "Family-style Thai food",
    "Family recipes",
    "DIY Pad Kra Pao",
  ],
  toneOfVoice: [
    "Warm",
    "Conversational",
    "Personal",
    "Playful",
    "Chatty",
    "Authentic",
    "Like a foodie friend sharing a genuine recommendation",
  ],
  avoid: [
    "Overly luxurious, corporate, formal, cold, or advertisement-like tone",
    "Forcing brand history into every post",
    "Listing questionnaire answers",
    "Inventing celebrity visits, Michelin, rankings, or viral claims",
    "作为一家 / 值得一提的是 / 不得不说 / 整体来说 / 这是一家非常值得 / 如果你正在寻找 / 无论是...还是...",
    "Excessive 不容错过 / 强烈推荐 / 绝对值得 / 无与伦比 / 极致体验 / 一口沦陷 / 必须冲 / 天花板 / 顶级 / 打造 / 带来极致体验",
  ],
  contentAngles: [
    "First-time discovery",
    "Unexpected discovery",
    "Hidden gem discovery",
    "Dish-focused recommendation",
    "Personal food reaction",
    "Favorite dish / what I would order again",
    "What to order guide",
    "Friend-recommended restaurant",
    "Group dining / sharing",
    "Family-style meal",
    "Casual food diary",
    "Tourist perspective",
    "Local perspective",
    "Repeat customer experience",
    "Bangkok travel recommendation",
    "Convenient after shopping",
    "Practical dining recommendation",
    "Atmosphere / casual dining",
    "Home-like feeling",
  ],
  referencePosts: [
    {
      id: "reference-01",
      title: "Tourist + classic restaurant + practical tip",
      characteristics: [
        "Starts from a travel or location situation",
        "Mixes personal experience with useful information",
        "Moderate enthusiasm",
        "Simple food descriptions without restaurant jargon",
      ],
      usefulFor: ["Tourists", "First-time visitors", "Practical recommendations"],
      contentAngles: ["Bangkok travel recommendation", "First-time discovery", "Practical recommendation"],
      doNotCopy: [
        "Exact mom's-cooking phrasing",
        "Exact recommendation structure",
        "Any free-drink tip format",
      ],
    },
    {
      id: "reference-02",
      title: "Dish-first + strong food reaction",
      characteristics: [
        "Opens on one dish, not the restaurant name",
        "Personal comparison and surprise",
        "Brand meaning appears only as supporting context",
        "Highly personal and food-driven",
      ],
      usefulFor: ["Customers who selected a specific dish"],
      contentAngles: [
        "Dish-focused recommendation",
        "Unexpected favorite dish",
        "Personal food reaction",
        "What I would order again",
      ],
      doNotCopy: ["Original comparison", "Original hook", "Explanation of the restaurant name"],
    },
    {
      id: "reference-03",
      title: "Brand story + signature dish guide",
      characteristics: [
        "Narrative and informative",
        "Brand story integrated with food, not as an ad",
        "Useful when the diner wants context before visiting",
      ],
      usefulFor: ["First-time discovery that genuinely needs context"],
      contentAngles: ["Brand story discovery", "What to order guide", "Bangkok restaurant recommendation"],
      doNotCopy: [
        "1999 founding recap as a default opening",
        "Auntie Ying biography",
        "Siam Square origin lecture",
        "This structure as the default for every post",
      ],
    },
    {
      id: "reference-04",
      title: "Casual travel POV",
      characteristics: [
        "Discovery-oriented and low-pressure",
        "Environment + food + convenience",
        "Sounds like a spontaneous travel diary",
      ],
      usefulFor: ["Tourists", "Shopping-day meals", "Casual first visits"],
      contentAngles: [
        "Hidden gem discovery",
        "First-time discovery",
        "Bangkok travel recommendation",
        "Casual food diary",
      ],
      doNotCopy: ["Exact discovery sequence", "Exact spice or sharing claims unless supported"],
    },
    {
      id: "reference-05",
      title: "Friend / colleague + group dining",
      characteristics: [
        "Social context first",
        "Food is part of what happened, not a brochure",
        "Casual diary language",
        "Strong UGC feeling",
      ],
      usefulFor: ["Group meals", "Sharing many dishes", "Repeat visits"],
      contentAngles: [
        "Friend-recommended restaurant",
        "Group dining / sharing",
        "Casual food diary",
        "Repeat customer experience",
      ],
      doNotCopy: ["Office-colleague setup", "Exact informal slang", "Invented dining companions"],
    },
    {
      id: "reference-06",
      title: "Local recommendation + trust",
      characteristics: [
        "Local perspective and credibility",
        "Personal experience first",
        "Approachable, not tourist-brochure",
      ],
      usefulFor: ["Local customers", "Tourists framed as discovering a local favorite"],
      contentAngles: ["Local perspective", "Friend recommendation", "Hidden gem discovery"],
      doNotCopy: ["Celebrity visits", "Social-proof fame claims", "Affordability claims unless provided"],
    },
    {
      id: "reference-07",
      title: "Concise practical recommendation",
      characteristics: [
        "Short and direct",
        "Practical usefulness",
        "Minimal emotional exaggeration",
      ],
      usefulFor: ["Sparse customer answers", "Practical recommendations"],
      contentAngles: ["Practical recommendation", "What to order guide", "Bangkok travel recommendation"],
      doNotCopy: ["A short template used for every sparse input"],
    },
    {
      id: "reference-08",
      title: "Casual + dish reaction",
      characteristics: [
        "Highly specific dish reactions",
        "Accessible, not luxurious",
        "Personal preference over prestige",
      ],
      usefulFor: ["Casual dining", "Dish-focused posts"],
      contentAngles: [
        "Dish-focused recommendation",
        "Personal food reaction",
        "Practical recommendation",
        "What I would order again",
      ],
      doNotCopy: ["Student/budget framing", "University setting", "Price claims"],
    },
    {
      id: "reference-09",
      title: "Friend recommendation + multiple dishes",
      characteristics: [
        "How I found it → what I ordered → what surprised me → what I would recommend",
        "Natural dish-by-dish reactions, not a menu list",
      ],
      usefulFor: ["Multiple selected dishes", "Friend/local signals"],
      contentAngles: [
        "Friend recommendation",
        "Unexpected favorite",
        "What I would order again",
        "Casual food diary",
      ],
      doNotCopy: ["Celebrity/social proof", "Value/price claims unless provided"],
    },
    {
      id: "reference-10",
      title: "Home-like local feeling",
      characteristics: [
        "Atmosphere-driven warmth",
        "Familiar, comfortable, home-like emotional territory",
        "Specific food plus practical information",
      ],
      usefulFor: ["Atmosphere selected", "Home-style comfort", "Casual dining"],
      contentAngles: [
        "Hidden gem discovery",
        "Atmosphere",
        "Thai home-style experience",
        "Casual dining",
        "First-time discovery",
      ],
      doNotCopy: [
        "Greenery/retro imagery",
        "Visiting a Thai friend's home as an exact phrase",
        "Invented interior descriptions",
      ],
    },
  ],
};
