import type { ContentStrategyLibrary } from "@/lib/content-strategy/types";

export const BAAN_YING_CONTENT_STRATEGY: ContentStrategyLibrary = {
  ksps: [
    {
      id: "KSP-01",
      name: "Authentic Thai Dining",
      purpose: "Communicate a natural and authentic Thai dining experience.",
      useWhen: [
        "Customer is discovering Thai food",
        "Customer describes food as authentic / traditional / natural",
        "Photos strongly show Thai dishes",
        "The dining experience itself is the main point",
      ],
      avoid: ["Do not invent authenticity claims without customer evidence"],
    },
    {
      id: "KSP-02",
      name: "Thai Home-Style Comfort",
      purpose: "Communicate home-style, comfortable, warm Thai dining.",
      useWhen: [
        "Customer describes food as comforting",
        "Customer mentions warmth / home-style feeling",
        "Dining atmosphere feels relaxed",
        "Food experience is casual and comforting",
      ],
      avoid: [],
    },
    {
      id: "KSP-03",
      name: "Family Recipes & Heritage",
      purpose: "Communicate family recipes, heritage, and long-term culinary identity.",
      frequency: "low",
      useWhen: [
        "Heritage / family-recipe framing naturally fits THIS meal",
        "Official brand context supports a light heritage aside",
      ],
      avoid: [
        "LOW-FREQUENCY. Do not automatically mention 1999, Auntie Ying, Siam Square, or brand history",
        "Do not turn every post into a brand-history post",
      ],
    },
    {
      id: "KSP-04",
      name: "Signature Thai Dishes",
      purpose: "Focus on memorable / signature Thai dishes.",
      useWhen: [
        "Customer strongly likes a specific dish",
        "A dish visually dominates the photos",
        "Customer explicitly recommends a dish",
        "Dish discovery is the strongest content opportunity",
      ],
      avoid: ["Do not invent dishes the customer did not select or mention"],
    },
    {
      id: "KSP-05",
      name: "Sharing & Togetherness",
      purpose: "Communicate the joy of sharing Thai food together.",
      useWhen: [
        "Friends dine together",
        "Family dining",
        "Group meal",
        "Multiple dishes are clearly shared",
      ],
      avoid: ["Do not invent who the customer was dining with"],
    },
    {
      id: "KSP-06",
      name: "Bangkok Lifestyle Dining",
      purpose: "Naturally position the restaurant within Bangkok travel, shopping, lifestyle, and dining routines.",
      useWhen: [
        "Branch is inside / near a shopping destination",
        "Customer is traveling",
        "Dining is part of a Bangkok itinerary",
        "Customer mentions shopping / travel / sightseeing",
      ],
      avoid: ["Do not force shopping context if it was not provided"],
    },
    {
      id: "KSP-07",
      name: "Multiple Bangkok Locations",
      purpose: "Communicate that the restaurant can be encountered at different Bangkok locations.",
      useWhen: [
        "Branch / location is relevant",
        "Customer experience benefits from location context",
        "Location convenience is genuinely relevant",
      ],
      avoid: ["Do not make unsupported claims about the total number of branches"],
    },
    {
      id: "KSP-08",
      name: "Everyday Thai Dining",
      purpose: "Show that Thai food can naturally fit into everyday lunch / dinner moments.",
      useWhen: [
        "Customer describes a normal meal",
        "No special occasion is present",
        "Casual dining is the strongest angle",
      ],
      avoid: [],
    },
    {
      id: "KSP-09",
      name: "Approachable Thai Flavors",
      purpose: "Make Thai food feel easy to discover, choose, and enjoy.",
      useWhen: [
        "Customer is visiting Baan Ying for the first time",
        "Customer explicitly says dishes are easy to enjoy",
        "Customer needs help choosing Thai food",
      ],
      avoid: [
        "Do not invent not spicy / beginner friendly / everyone can eat it / mild / no strong flavors unless supported",
      ],
    },
    {
      id: "KSP-10",
      name: "A Place to Return To",
      purpose: "Create a natural feeling that the restaurant is somewhere worth coming back to.",
      useWhen: [
        "Customer explicitly mentions returning",
        "Customer says they liked it enough to revisit",
        "Customer has repeat-visit information",
        "Customer expresses future intent",
      ],
      avoid: ["Do not claim the customer is a repeat customer unless the data confirms it"],
    },
  ],
  storylines: [
    {
      id: "ST-01",
      name: "Discovering Thai Comfort Food",
      narrativeIntention: "The customer discovers a Thai dining experience that feels worth noticing.",
      avoid: ["Do not force a fixed opening such as 第一次来曼谷"],
    },
    {
      id: "ST-02",
      name: "The Thai Dishes You Keep Thinking About",
      narrativeIntention: "Build the story around memorable dishes.",
      avoid: ["Do not force a fixed opening such as 这次最喜欢的是"],
    },
    {
      id: "ST-03",
      name: "A Taste of Home in Bangkok",
      narrativeIntention: "Create a warm, home-style, comforting Thai dining story.",
      avoid: [],
    },
    {
      id: "ST-04",
      name: "Bangkok Dining, The Easy Way",
      narrativeIntention: "Naturally place the restaurant into a Bangkok shopping / travel / dining itinerary.",
      avoid: ["Do not force a fixed opening such as 逛完商场"],
    },
    {
      id: "ST-05",
      name: "Come Together Over Thai Food",
      narrativeIntention: "Build around sharing food and spending time together.",
      avoid: ["People / togetherness only if customer evidence supports companions"],
    },
    {
      id: "ST-06",
      name: "From First Visit to Favourite",
      narrativeIntention: "Tell a story of discovery → liking → possible repeat preference. Do NOT automatically claim repeat visits.",
      avoid: ["Do not invent repeat-visit history"],
    },
    {
      id: "ST-07",
      name: "Your Kind of Thai Food",
      narrativeIntention: "Show that different customers can connect with Thai food for different reasons.",
      avoid: [],
    },
    {
      id: "ST-08",
      name: "A Thai Meal Worth Sharing",
      narrativeIntention: "Focus on a meal / table / dishes that naturally feels worth sharing. This is the meal itself, not the people story of ST-05.",
      avoid: [],
    },
    {
      id: "ST-09",
      name: "Little Moments at Baan Ying",
      narrativeIntention: "Create a casual, authentic UGC moment. Real customer diary, not a formal advertisement.",
      avoid: [],
    },
    {
      id: "ST-10",
      name: "Making Bangkok Food Memories",
      narrativeIntention: "Connect the dining experience with Bangkok travel, lifestyle, or personal memories.",
      avoid: [],
    },
  ],
  contentAngles: [
    {
      id: "CA-01",
      name: "First-Time Discovery",
      purpose: "A first encounter with the restaurant or Thai dining that feels newly noticed.",
      useWhen: ["First visit", "First-time discovery energy"],
      avoid: ["Do not use if visit frequency is a confirmed heavy repeat"],
    },
    {
      id: "CA-02",
      name: "Hero Dish",
      purpose: "Center the post on one memorable dish.",
      useWhen: ["Customer strongly recommends a dish", "A dish dominates photos"],
      avoid: ["Do not invent a hero dish"],
    },
    {
      id: "CA-03",
      name: "Taste Reaction",
      purpose: "Lead with a personal reaction to flavor / texture / satisfaction.",
      useWhen: ["Customer named taste qualities", "Food reaction is the strongest moment"],
      avoid: ["Do not invent spice, texture, or cooking methods"],
    },
    {
      id: "CA-04",
      name: "Tourist Perspective",
      purpose: "Write from a traveler discovering Bangkok food.",
      useWhen: ["Customer is a tourist"],
      avoid: ["Do not use a tourist voice for locals"],
    },
    {
      id: "CA-05",
      name: "Local Lifestyle",
      purpose: "Write as everyday Bangkok / local dining, not a travel guide.",
      useWhen: ["Customer is a local"],
      avoid: ["Do not explain basic Bangkok tourist info"],
    },
    {
      id: "CA-06",
      name: "Repeat Customer",
      purpose: "Write as someone returning because they already like it.",
      useWhen: ["Not first visit", "Customer explicitly mentions returning"],
      avoid: ["Do not claim repeat visits without data"],
    },
    {
      id: "CA-07",
      name: "Friends Dining",
      purpose: "A meal shared with friends.",
      useWhen: ["Customer evidence of friends / group dining"],
      avoid: ["Do not invent companions"],
    },
    {
      id: "CA-08",
      name: "Family Dining",
      purpose: "A meal shared with family.",
      useWhen: ["Customer evidence of family dining"],
      avoid: ["Do not invent family companions"],
    },
    {
      id: "CA-09",
      name: "Bangkok Itinerary",
      purpose: "Dining as part of shopping, travel, or a Bangkok day out.",
      useWhen: ["Tourist + mall / shopping / itinerary context"],
      avoid: ["Do not force mall context if not provided"],
    },
    {
      id: "CA-10",
      name: "Practical Recommendation",
      purpose: "A useful, concrete recommendation a friend could act on.",
      useWhen: ["Customer wants to recommend what / where to eat"],
      avoid: ["Do not become a generic ranking list"],
    },
    {
      id: "CA-11",
      name: "Casual Food Diary",
      purpose: "A loose, real UGC diary of this meal.",
      useWhen: ["Ordinary lunch / dinner", "No special occasion"],
      avoid: ["Do not polish into an advertisement"],
    },
    {
      id: "CA-12",
      name: "Food Memory",
      purpose: "Connect the meal to a personal Bangkok / travel / life memory.",
      useWhen: ["Travel, lifestyle, or memory framing is supported"],
      avoid: ["Do not invent memories"],
    },
  ],
  searchKeywords: {
    primary: [
      "曼谷美食",
      "曼谷泰餐",
      "曼谷泰菜",
      "曼谷餐厅",
      "曼谷吃什么",
      "曼谷美食推荐",
      "曼谷吃饭",
      "曼谷探店",
      "曼谷美食攻略",
    ],
    secondary: [
      "曼谷泰国菜",
      "曼谷餐厅推荐",
      "曼谷美食分享",
      "曼谷用餐",
      "曼谷旅行美食",
      "曼谷逛街吃饭",
      "曼谷美食打卡",
      "泰国菜推荐",
      "泰国美食",
    ],
  },
  compatibility: {
    kspToStorylines: {
      "KSP-01": ["ST-01", "ST-02", "ST-07"],
      "KSP-02": ["ST-03", "ST-09", "ST-10"],
      "KSP-03": ["ST-03", "ST-06", "ST-10"],
      "KSP-04": ["ST-02", "ST-08", "ST-01"],
      "KSP-05": ["ST-05", "ST-08", "ST-10"],
      "KSP-06": ["ST-04", "ST-10", "ST-07"],
      "KSP-07": ["ST-04", "ST-01", "ST-07"],
      "KSP-08": ["ST-09", "ST-04", "ST-05"],
      "KSP-09": ["ST-07", "ST-01", "ST-02"],
      "KSP-10": ["ST-06", "ST-09", "ST-10"],
    },
    storylineToAngles: {
      "ST-01": ["CA-01", "CA-04", "CA-11"],
      "ST-02": ["CA-02", "CA-03", "CA-10"],
      "ST-03": ["CA-03", "CA-08", "CA-11"],
      "ST-04": ["CA-09", "CA-10", "CA-04"],
      "ST-05": ["CA-07", "CA-08", "CA-12"],
      "ST-06": ["CA-06", "CA-02", "CA-03"],
      "ST-07": ["CA-04", "CA-05", "CA-10"],
      "ST-08": ["CA-07", "CA-08", "CA-02"],
      "ST-09": ["CA-11", "CA-03", "CA-12"],
      "ST-10": ["CA-12", "CA-04", "CA-07"],
    },
    storylineAngleToKeywords: {
      "ST-01+CA-01": ["曼谷美食", "曼谷泰餐"],
      "ST-01+CA-04": ["曼谷吃什么", "曼谷美食推荐"],
      "ST-01+CA-11": ["曼谷探店", "曼谷美食"],
      "ST-02+CA-02": ["曼谷泰菜", "曼谷泰餐"],
      "ST-02+CA-03": ["曼谷美食", "泰国菜推荐"],
      "ST-02+CA-10": ["曼谷美食推荐", "曼谷吃什么"],
      "ST-03+CA-03": ["曼谷泰餐", "曼谷泰菜"],
      "ST-03+CA-08": ["曼谷餐厅", "曼谷吃饭"],
      "ST-03+CA-11": ["曼谷泰餐", "曼谷探店"],
      "ST-04+CA-09": ["曼谷吃饭", "曼谷餐厅"],
      "ST-04+CA-10": ["曼谷美食攻略", "曼谷美食推荐"],
      "ST-04+CA-04": ["曼谷吃什么", "曼谷旅行美食"],
      "ST-05+CA-07": ["曼谷餐厅", "曼谷吃饭"],
      "ST-05+CA-08": ["曼谷泰餐", "曼谷餐厅"],
      "ST-05+CA-12": ["曼谷美食", "曼谷美食分享"],
      "ST-06+CA-06": ["曼谷美食", "曼谷泰餐"],
      "ST-06+CA-02": ["曼谷泰菜", "曼谷美食推荐"],
      "ST-06+CA-03": ["曼谷泰餐", "曼谷美食"],
      "ST-07+CA-04": ["曼谷吃什么", "曼谷泰菜"],
      "ST-07+CA-05": ["曼谷美食", "曼谷吃饭"],
      "ST-07+CA-10": ["曼谷美食推荐"],
      "ST-08+CA-07": ["曼谷泰餐", "曼谷美食"],
      "ST-08+CA-08": ["曼谷餐厅", "曼谷吃饭"],
      "ST-08+CA-02": ["曼谷美食推荐", "曼谷泰菜"],
      "ST-09+CA-11": ["曼谷探店", "曼谷美食"],
      "ST-09+CA-03": ["曼谷探店", "曼谷泰餐"],
      "ST-09+CA-12": ["曼谷美食", "曼谷探店"],
      "ST-10+CA-12": ["曼谷美食", "曼谷旅行美食"],
      "ST-10+CA-04": ["曼谷吃什么", "曼谷美食推荐"],
      "ST-10+CA-07": ["曼谷吃饭", "曼谷美食分享"],
    },
  },
};
