import {
  CANVAS_WIDTH,
  CANVAS_HEIGHT,
  SAFE_AREA,
  type CoverTemplate,
} from "./types";

const W = CANVAS_WIDTH;
const SAFE = SAFE_AREA;

export const COLORS = {
  green: "#24662d",
  black: "#0f0f0f",
  yellow: "#fac414",
  white: "#ffffff",
  red: "#c91c1c",
} as const;

export const TEMPLATES: CoverTemplate[] = [
  {
    id: "top-stroke",
    name: "Style 1",
    layout: "collage",
    overlay: null,
    safeArea: SAFE,
    badgeStyle: "plain",
    decoration: [],
    slots: {
      title: {
        x: 72,
        y: 108,
        maxWidth: 936,
        font: "jiangchengheiti",
        size: 160,
        fill: COLORS.yellow,
        stroke: { color: COLORS.black, width: 10 },
        dropShadow: { x: 0, y: 4, color: COLORS.black },
        align: "center",
        lineHeight: 1.08,
        maxHeight: 420,
      },
      subtitle: {
        x: 90,
        y: 300,
        maxWidth: 900,
        font: "jiangchengheiti",
        size: 80,
        fill: COLORS.yellow,
        stroke: { color: COLORS.black, width: 10 },
        align: "center",
        lineHeight: 1.2,
        maxHeight: 180,
      },
      badge: {
        x: SAFE,
        y: 400,
        maxWidth: 420,
        font: "jiangchengheiti",
        size: 28,
        fill: COLORS.yellow,
        stroke: { color: COLORS.black, width: 10 },
        align: "left",
      },
    },
  },
  {
    id: "bottom-bar",
    name: "Style 8",
    layout: "single",
    overlay: {
      position: "bottom",
      direction: "transparent-to-bottom",
      opacity: 0.18,
      color: COLORS.black,
    },
    safeArea: SAFE,
    badgeStyle: "plain",
    textStyle: { kind: "outline-stack", gap: 8, subtitleGap: 52 },
    decoration: [
      {
        type: "sparkle",
        x: 86,
        y: 520,
        size: 18,
        fill: COLORS.white,
      },
      {
        type: "sparkle",
        x: 968,
        y: 780,
        size: 16,
        fill: COLORS.white,
        opacity: 0.9,
      },
    ],
    slots: {
      title: {
        x: SAFE,
        y: 500,
        maxWidth: W - SAFE * 2,
        font: "jiangchengheiti",
        size: 160,
        fill: COLORS.green,
        stroke: { color: COLORS.white, width: 12 },
        dropShadow: { x: 5, y: 7, color: COLORS.black },
        align: "center",
        lineHeight: 1.08,
        maxHeight: 420,
        minSize: 104,
      },
      subtitle: {
        x: SAFE,
        y: 720,
        maxWidth: W - SAFE * 2,
        font: "jiangchengheiti",
        size: 80,
        fill: COLORS.green,
        stroke: { color: COLORS.white, width: 12 },
        dropShadow: { x: 5, y: 7, color: COLORS.black },
        align: "center",
        lineHeight: 1.08,
        maxHeight: 220,
        minSize: 104,
      },
      badge: {
        x: SAFE,
        y: 56,
        maxWidth: 320,
        font: "jiangchengheiti",
        size: 22,
        fill: COLORS.green,
        stroke: { color: COLORS.white, width: 6 },
        dropShadow: { x: 3, y: 4, color: COLORS.black },
        align: "center",
      },
    },
  },
  {
    id: "bottom-card",
    name: "Style 10",
    layout: "single",
    overlay: {
      position: "bottom",
      direction: "transparent-to-bottom",
      opacity: 0.12,
      color: COLORS.black,
    },
    safeArea: SAFE,
    badgeStyle: "capsule",
    badgeBackground: COLORS.yellow,
    decoration: [
      {
        type: "rect",
        x: 70,
        y: 480,
        width: 940,
        height: 330,
        fill: COLORS.white,
        radius: 24,
      },
      {
        type: "rect",
        x: 96,
        y: 508,
        width: 8,
        height: 274,
        fill: COLORS.yellow,
        radius: 5,
      },
    ],
    slots: {
      title: {
        x: 128,
        y: 536,
        maxWidth: 820,
        font: "jiangchengheiti",
        size: 126,
        fill: COLORS.black,
        align: "left",
        lineHeight: 1.14,
        maxHeight: 260,
        minSize: 96,
      },
      subtitle: {
        x: 128,
        y: 700,
        maxWidth: 820,
        font: "jiangchengheiti",
        size: 64,
        fill: COLORS.black,
        align: "left",
        lineHeight: 1.14,
        maxHeight: 140,
        minSize: 40,
      },
      badge: {
        x: 760,
        y: 548,
        maxWidth: 220,
        font: "jiangchengheiti",
        size: 20,
        fill: COLORS.black,
        align: "right",
      },
    },
  },
  {
    id: "top-banner",
    name: "Style 4",
    layout: "single",
    overlay: {
      position: "top",
      direction: "top-to-transparent",
      opacity: 0.1,
      color: COLORS.black,
    },
    safeArea: SAFE,
    badgeStyle: "capsule",
    badgeBackground: COLORS.white,
    decoration: [
      {
        type: "rect",
        x: 0,
        y: 278,
        width: W,
        height: 268,
        fill: COLORS.green,
      },
    ],
    slots: {
      title: {
        x: SAFE,
        y: 316,
        maxWidth: W - SAFE * 2,
        font: "jiangchengheiti",
        size: 116,
        fill: COLORS.white,
        align: "center",
        lineHeight: 1.16,
        maxHeight: 200,
        minSize: 72,
      },
      subtitle: {
        x: SAFE,
        y: 396,
        maxWidth: W - SAFE * 2,
        font: "jiangchengheiti",
        size: 116,
        fill: COLORS.white,
        align: "center",
        lineHeight: 1.16,
        maxHeight: 140,
        minSize: 72,
      },
      badge: {
        x: SAFE,
        y: 480,
        maxWidth: 360,
        font: "jiangchengheiti",
        size: 22,
        fill: COLORS.white,
        align: "left",
      },
    },
  },
  {
    id: "left-spine",
    name: "Style 5",
    layout: "single",
    overlay: {
      position: "top",
      direction: "top-to-transparent",
      opacity: 0.14,
      color: COLORS.black,
    },
    safeArea: SAFE,
    badgeStyle: "capsule",
    badgeBackground: COLORS.black,
    decoration: [
      {
        type: "rect",
        x: 40,
        y: 40,
        width: W - 80,
        height: CANVAS_HEIGHT - 80,
        fill: "transparent",
        borderWidth: 8,
        borderColor: COLORS.yellow,
        radius: 32,
      },
      {
        type: "gradient",
        x: 0,
        y: 1120,
        width: W,
        height: 230,
        direction: "transparent-to-bottom",
        color: COLORS.black,
        opacity: 0.16,
      },
    ],
    slots: {
      title: {
        x: SAFE,
        y: 264,
        maxWidth: W - SAFE * 2,
        font: "jiangchengheiti",
        size: 128,
        fill: COLORS.yellow,
        stroke: { color: COLORS.black, width: 8 },
        dropShadow: { x: 5, y: 8, color: COLORS.black },
        align: "center",
        lineHeight: 1.26,
        maxHeight: 380,
        minSize: 104,
      },
      subtitle: {
        x: SAFE,
        y: 400,
        maxWidth: W - SAFE * 2,
        font: "jiangchengheiti",
        size: 128,
        fill: COLORS.yellow,
        stroke: { color: COLORS.black, width: 8 },
        dropShadow: { x: 5, y: 8, color: COLORS.black },
        align: "center",
        lineHeight: 1.26,
        maxHeight: 220,
        minSize: 104,
      },
      badge: {
        x: SAFE,
        y: 52,
        maxWidth: 280,
        font: "jiangchengheiti",
        size: 20,
        fill: COLORS.yellow,
        align: "left",
      },
    },
  },
  {
    id: "polaroid",
    name: "Style 6",
    layout: "single",
    overlay: null,
    safeArea: SAFE,
    badgeStyle: "plain",
    decoration: [
      {
        type: "polaroid-frame",
        inset: 42,
        bottomExtra: 300,
        fill: COLORS.white,
      },
      {
        type: "rect",
        x: 86,
        y: 18,
        width: 160,
        height: 38,
        fill: "#efe6d6",
        opacity: 0.88,
        rotate: -12,
        radius: 4,
      },
      {
        type: "rect",
        x: 820,
        y: 8,
        width: 150,
        height: 34,
        fill: "#efe6d6",
        opacity: 0.86,
        rotate: 11,
        radius: 4,
      },
    ],
    slots: {
      title: {
        x: 66,
        y: 1088,
        maxWidth: W - 132,
        font: "jiangchengheiti",
        size: 118,
        fill: COLORS.black,
        align: "center",
        lineHeight: 1.1,
        maxHeight: 240,
        minSize: 96,
      },
      subtitle: {
        x: 66,
        y: 1200,
        maxWidth: W - 132,
        font: "jiangchengheiti",
        size: 118,
        fill: COLORS.black,
        align: "center",
        lineHeight: 1.1,
        maxHeight: 140,
        minSize: 96,
      },
      badge: {
        x: 72,
        y: 1130,
        maxWidth: 280,
        font: "jiangchengheiti",
        size: 20,
        fill: COLORS.black,
        align: "center",
      },
    },
  },
  {
    id: "center-lower",
    name: "Style 7",
    layout: "single",
    overlay: {
      position: "bottom",
      direction: "transparent-to-bottom",
      opacity: 0.2,
      color: COLORS.black,
    },
    safeArea: SAFE,
    badgeStyle: "plain",
    decoration: [],
    slots: {
      title: {
        x: 52,
        y: 240,
        maxWidth: 950,
        font: "jiangchengheiti",
        size: 164,
        fill: COLORS.red,
        stroke: { color: COLORS.white, width: 11 },
        align: "left",
        lineHeight: 1.1,
        maxHeight: 360,
      },
      subtitle: {
        x: SAFE,
        y: 400,
        maxWidth: W - SAFE * 2,
        font: "jiangchengheiti",
        size: 64,
        fill: COLORS.white,
        stroke: { color: COLORS.red, width: 11 },
        align: "left",
        lineHeight: 1.2,
        maxHeight: 150,
      },
      badge: {
        x: SAFE,
        y: 516,
        maxWidth: 400,
        font: "jiangchengheiti",
        size: 26,
        fill: COLORS.white,
        stroke: { color: COLORS.red, width: 12 },
        align: "left",
      },
    },
  },
  {
    id: "badge-stack",
    name: "Style 2",
    layout: "single",
    overlay: {
      position: "bottom",
      direction: "transparent-to-bottom",
      opacity: 0.08,
      color: COLORS.black,
    },
    safeArea: SAFE,
    badgeStyle: "plain",
    textStyle: { kind: "chips", gap: 10 },
    decoration: [],
    slots: {
      title: {
        x: SAFE,
        y: 108,
        maxWidth: 860,
        font: "jiangchengheiti",
        size: 88,
        fill: COLORS.black,
        align: "center",
        lineHeight: 1.12,
        maxHeight: 240,
        minSize: 56,
      },
      subtitle: {
        x: SAFE,
        y: 280,
        maxWidth: 820,
        font: "jiangchengheiti",
        size: 56,
        fill: COLORS.black,
        align: "center",
        lineHeight: 1.15,
        maxHeight: 90,
        minSize: 40,
      },
      badge: {
        x: SAFE,
        y: 56,
        maxWidth: 320,
        font: "jiangchengheiti",
        size: 22,
        fill: COLORS.black,
        align: "center",
      },
    },
  },
  {
    id: "split-band",
    name: "Style 9",
    layout: "single",
    overlay: {
      position: "top",
      direction: "top-to-transparent",
      opacity: 0.08,
      color: COLORS.black,
    },
    safeArea: SAFE,
    badgeStyle: "plain",
    textStyle: { kind: "slant-stickers", rotate: -12, gap: 10 },
    decoration: [],
    slots: {
      title: {
        x: SAFE,
        y: 108,
        maxWidth: 880,
        font: "jiangchengheiti",
        size: 88,
        fill: COLORS.black,
        align: "center",
        lineHeight: 1.08,
        maxHeight: 240,
        minSize: 60,
      },
      subtitle: {
        x: SAFE,
        y: 290,
        maxWidth: 840,
        font: "jiangchengheiti",
        size: 60,
        fill: COLORS.black,
        align: "center",
        lineHeight: 1.12,
        maxHeight: 120,
        minSize: 44,
      },
      badge: {
        x: SAFE,
        y: 56,
        maxWidth: 280,
        font: "jiangchengheiti",
        size: 20,
        fill: COLORS.black,
        align: "center",
      },
    },
  },
  {
    id: "dual-line",
    name: "Style 3",
    layout: "single",
    overlay: {
      position: "top",
      direction: "top-to-transparent",
      opacity: 0.06,
      color: COLORS.black,
    },
    safeArea: SAFE,
    badgeStyle: "plain",
    textStyle: { kind: "blob-stickers", gap: 12 },
    decoration: [
      {
        type: "sparkle",
        x: 132,
        y: 560,
        size: 16,
        fill: COLORS.yellow,
      },
      {
        type: "sparkle",
        x: 900,
        y: 584,
        size: 14,
        fill: COLORS.yellow,
      },
      {
        type: "sparkle",
        x: 780,
        y: 792,
        size: 12,
        fill: COLORS.yellow,
        opacity: 0.9,
      },
    ],
    slots: {
      title: {
        x: SAFE,
        y: 108,
        maxWidth: 900,
        font: "jiangchengheiti",
        size: 132,
        fill: COLORS.black,
        align: "center",
        lineHeight: 1.1,
        maxHeight: 340,
        minSize: 104,
      },
      subtitle: {
        x: SAFE,
        y: 300,
        maxWidth: 820,
        font: "jiangchengheiti",
        size: 132,
        fill: COLORS.black,
        align: "center",
        lineHeight: 1.1,
        maxHeight: 180,
        minSize: 104,
      },
      badge: {
        x: SAFE,
        y: 40,
        maxWidth: 240,
        font: "jiangchengheiti",
        size: 22,
        fill: COLORS.white,
        align: "center",
      },
    },
  },
];

export const TEMPLATE_IDS = TEMPLATES.map((template) => template.id);

export function getTemplate(id: string): CoverTemplate | undefined {
  return TEMPLATES.find((template) => template.id === id);
}

export function listTemplates(): Array<{ id: string; name: string }> {
  return TEMPLATES.map(({ id, name }) => ({ id, name }));
}
